ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_to_use    INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_earned    INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_processed BOOLEAN DEFAULT FALSE;
